package owasp

// CWEToOWASP maps Common Weakness Enumeration IDs to OWASP Top 10:2025 categories.
//
// This table is the second layer in our 3-layer mapping strategy:
//   1. Direct metadata from tools (e.g., Semgrep provides OWASP tags directly)
//   2. CWE→OWASP lookup (this table)
//   3. Heuristic fallback (rule ID / message keyword matching)
//
// Sources:
//   - OWASP CWE mapping spreadsheet (https://owasp.org/Top10/A00_2021-How_to_use_the_OWASP_Top_10_as_a_Standard/)
//   - MITRE CWE database cross-references
//
// Coverage: ~100 CWE IDs across all 10 categories.
var CWEToOWASP = map[string]OwaspMapping{
	// A01: Broken Access Control
	"CWE-22":  {Category: "A01", Label: "Broken Access Control"},
	"CWE-23":  {Category: "A01", Label: "Broken Access Control"},
	"CWE-35":  {Category: "A01", Label: "Broken Access Control"},
	"CWE-59":  {Category: "A01", Label: "Broken Access Control"},
	"CWE-200": {Category: "A01", Label: "Broken Access Control"},
	"CWE-201": {Category: "A01", Label: "Broken Access Control"},
	"CWE-219": {Category: "A01", Label: "Broken Access Control"},
	"CWE-264": {Category: "A01", Label: "Broken Access Control"},
	"CWE-275": {Category: "A01", Label: "Broken Access Control"},
	"CWE-276": {Category: "A01", Label: "Broken Access Control"},
	"CWE-284": {Category: "A01", Label: "Broken Access Control"},
	"CWE-285": {Category: "A01", Label: "Broken Access Control"},
	"CWE-352": {Category: "A01", Label: "Broken Access Control"},
	"CWE-359": {Category: "A01", Label: "Broken Access Control"},
	"CWE-377": {Category: "A01", Label: "Broken Access Control"},
	"CWE-402": {Category: "A01", Label: "Broken Access Control"},
	"CWE-425": {Category: "A01", Label: "Broken Access Control"},
	"CWE-441": {Category: "A01", Label: "Broken Access Control"},
	"CWE-497": {Category: "A01", Label: "Broken Access Control"},
	"CWE-538": {Category: "A01", Label: "Broken Access Control"},
	"CWE-540": {Category: "A01", Label: "Broken Access Control"},
	"CWE-548": {Category: "A01", Label: "Broken Access Control"},
	"CWE-552": {Category: "A01", Label: "Broken Access Control"},
	"CWE-566": {Category: "A01", Label: "Broken Access Control"},
	"CWE-601": {Category: "A01", Label: "Broken Access Control"},
	"CWE-639": {Category: "A01", Label: "Broken Access Control"},
	"CWE-651": {Category: "A01", Label: "Broken Access Control"},
	"CWE-668": {Category: "A01", Label: "Broken Access Control"},
	"CWE-706": {Category: "A01", Label: "Broken Access Control"},
	"CWE-862": {Category: "A01", Label: "Broken Access Control"},
	"CWE-863": {Category: "A01", Label: "Broken Access Control"},
	"CWE-913": {Category: "A01", Label: "Broken Access Control"},

	// A02: Cryptographic Failures
	"CWE-261": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-296": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-310": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-319": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-321": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-322": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-323": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-324": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-325": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-326": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-327": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-328": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-329": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-330": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-331": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-335": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-336": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-338": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-340": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-347": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-523": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-720": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-757": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-759": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-760": {Category: "A02", Label: "Cryptographic Failures"},
	"CWE-818": {Category: "A02", Label: "Cryptographic Failures"},

	// A03: Injection
	"CWE-20":   {Category: "A03", Label: "Injection"},
	"CWE-74":   {Category: "A03", Label: "Injection"},
	"CWE-75":   {Category: "A03", Label: "Injection"},
	"CWE-77":   {Category: "A03", Label: "Injection"},
	"CWE-78":   {Category: "A03", Label: "Injection"},
	"CWE-79":   {Category: "A03", Label: "Injection"},
	"CWE-80":   {Category: "A03", Label: "Injection"},
	"CWE-83":   {Category: "A03", Label: "Injection"},
	"CWE-87":   {Category: "A03", Label: "Injection"},
	"CWE-88":   {Category: "A03", Label: "Injection"},
	"CWE-89":   {Category: "A03", Label: "Injection"},
	"CWE-90":   {Category: "A03", Label: "Injection"},
	"CWE-91":   {Category: "A03", Label: "Injection"},
	"CWE-93":   {Category: "A03", Label: "Injection"},
	"CWE-94":   {Category: "A03", Label: "Injection"},
	"CWE-95":   {Category: "A03", Label: "Injection"},
	"CWE-96":   {Category: "A03", Label: "Injection"},
	"CWE-97":   {Category: "A03", Label: "Injection"},
	"CWE-98":   {Category: "A03", Label: "Injection"},
	"CWE-99":   {Category: "A03", Label: "Injection"},
	"CWE-100":  {Category: "A03", Label: "Injection"},
	"CWE-113":  {Category: "A03", Label: "Injection"},
	"CWE-116":  {Category: "A03", Label: "Injection"},
	"CWE-138":  {Category: "A03", Label: "Injection"},
	"CWE-184":  {Category: "A03", Label: "Injection"},
	"CWE-470":  {Category: "A03", Label: "Injection"},
	"CWE-471":  {Category: "A03", Label: "Injection"},
	"CWE-564":  {Category: "A03", Label: "Injection"},
	"CWE-610":  {Category: "A03", Label: "Injection"},
	"CWE-643":  {Category: "A03", Label: "Injection"},
	"CWE-644":  {Category: "A03", Label: "Injection"},
	"CWE-652":  {Category: "A03", Label: "Injection"},
	"CWE-917":  {Category: "A03", Label: "Injection"},
	"CWE-1333": {Category: "A03", Label: "Injection"},

	// A04: Insecure Design
	"CWE-209":  {Category: "A04", Label: "Insecure Design"},
	"CWE-256":  {Category: "A04", Label: "Insecure Design"},
	"CWE-501":  {Category: "A04", Label: "Insecure Design"},
	"CWE-522":  {Category: "A04", Label: "Insecure Design"},
	"CWE-656":  {Category: "A04", Label: "Insecure Design"},
	"CWE-799":  {Category: "A04", Label: "Insecure Design"},
	// CWE-798 maps to A07 (hardcoded credentials → auth failures) as primary

	// A05: Security Misconfiguration
	"CWE-2":   {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-11":  {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-13":  {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-15":  {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-16":  {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-260": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-315": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-520": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-526": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-537": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-541": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-547": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-611": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-614": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-756": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-776": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-942": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-1004": {Category: "A05", Label: "Security Misconfiguration"},
	"CWE-1032": {Category: "A05", Label: "Security Misconfiguration"},

	// A06: Vulnerable and Outdated Components
	"CWE-937":  {Category: "A06", Label: "Vulnerable and Outdated Components"},
	"CWE-1035": {Category: "A06", Label: "Vulnerable and Outdated Components"},
	"CWE-1104": {Category: "A06", Label: "Vulnerable and Outdated Components"},

	// A07: Identification and Authentication Failures
	"CWE-255":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-259":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-287":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-288":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-290":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-294":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-295":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-297":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-300":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-302":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-304":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-306":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-307":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-346":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-384":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-521":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-613":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-620":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-640":  {Category: "A07", Label: "Identification and Authentication Failures"},
	"CWE-798":  {Category: "A07", Label: "Identification and Authentication Failures"},

	// A08: Software and Data Integrity Failures
	"CWE-345": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-353": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-426": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-494": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-502": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-565": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-784": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-829": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-830": {Category: "A08", Label: "Software and Data Integrity Failures"},
	"CWE-915": {Category: "A08", Label: "Software and Data Integrity Failures"},

	// A09: Security Logging and Monitoring Failures
	"CWE-117": {Category: "A09", Label: "Security Logging and Monitoring Failures"},
	"CWE-223": {Category: "A09", Label: "Security Logging and Monitoring Failures"},
	"CWE-532": {Category: "A09", Label: "Security Logging and Monitoring Failures"},
	"CWE-778": {Category: "A09", Label: "Security Logging and Monitoring Failures"},

	// A10: Server-Side Request Forgery (SSRF)
	"CWE-918": {Category: "A10", Label: "Server-Side Request Forgery"},
}
